[package]
name = "together-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "together"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
dialoguer = "0.11.0"
